Category
Olena-Pro/Book_store pull request #15
Opened 2024-05-06 10:39 UTC by Olena-Pro

2024-05-07 10:15 UTC, kerrrusha requested changes

2024-05-07 10:15 UTC, kerrrusha commented on src/main/java/mate/academy/bookstore/model/Category.java
> +            nullable = false)
not critical but in this case explicitly specifying column name is redundant as Hibernate will automatically map it (for example field name `isDeleted` will be mapped to `is_deleted` implicitly as default)
```suggestion
    @Column(nullable = false)
    private String name;
    private String description;
    @Column(nullable = false)
```

2024-05-07 10:15 UTC, kerrrusha commented on src/main/java/mate/academy/bookstore/security/JwtUtil.java
> +            return ! getClaimsFromToken(token, Claims::getExpiration).before(new Date());
extract `new Date()` into `today` variable

2024-05-07 10:15 UTC, kerrrusha commented on src/main/java/mate/academy/bookstore/service/BookService.java
> +
```suggestion
```

2024-05-07 10:15 UTC, kerrrusha commented on src/main/resources/db/changelog/changes/10-create-category-table.yaml
> +                  type: varchar(255)
description can be long
```suggestion
                  type: text
```

2024-05-07 10:15 UTC, kerrrusha commented on target/generated-sources/annotations/mate/academy/bookstore/mapper/impl/BookMapperImpl.java
target folder should not be included to git

2024-05-07 10:15 UTC, kerrrusha commented on target/generated-sources/annotations/mate/academy/bookstore/mapper/impl/CategoryMapperImpl.java
target folder should not be included to git

2024-05-08 06:39 UTC, Elena-Bruyako requested changes
Let's improve your solution!

2024-05-08 06:39 UTC, Elena-Bruyako commented on target/generated-sources/annotations/mate/academy/bookstore/mapper/impl/CategoryMapperImpl.java
> +public class CategoryMapperImpl implements CategoryMapper {
These classes shouldn't be visible, add target to gitignore

2024-05-08 06:39 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/controller/CategoryController.java
> +@RequestMapping(value = "/categories")
```suggestion
@RequestMapping("/categories")
```

2024-05-08 06:39 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/controller/CategoryController.java
> +                                      @RequestBody CategoryRequestDto requestDto) {
```suggestion
                                      @RequestBody @Valid CategoryRequestDto requestDto) {
```

2024-05-08 06:39 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/controller/CategoryController.java
> +    public List<BookWithoutCategoryDto> getBooksByCategoryId(@PathVariable Long id) {
```suggestion
    public List<BookWithoutCategoryDto> getBooksByCategoryId(@PathVariable @Positive Long id) {
```
Check other id 
Add `@Validated` under the controller

2024-05-08 06:39 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/dto/book/CreateBookRequestDto.java
>      @NotNull
For String is better use `@NotBlank`

2024-05-08 06:39 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/dto/category/CategoryRequestDto.java
> +public record CategoryRequestDto(
Add validation

2024-05-08 06:39 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/model/Book.java
> +    @ManyToMany(fetch = FetchType.EAGER)
Bad approach to use EAGER

2024-05-08 06:39 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/service/CategoryServiceImpl.java
> +        Category categoryWithId = categoryMapper.toModel(requestDto);
You can create in CategoryMapper method: 
`void updateCategoryFromDto(CategoryRequestDto requestDto, @MappingTarget Category category);`
and use it here

2024-05-08 06:39 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/11-create-books-categouries-table.yaml
> +databaseChangeLog:
fix the mistake in the file name

2024-05-08 06:39 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/11-create-books-categouries-table.yaml
> +                  type: bigint
constraints ?

2024-05-08 06:39 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/11-create-books-categouries-table.yaml
> +                  type: bigint
constraints ?

2024-05-08 06:39 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/12-add-fks-in-books_categories-table.yaml
> +      id: add-forign-keys-in-books-categories
Don't need to create addForeignKeyConstraint here, you can add them in the create-books_categories-table changelog

2024-05-09 07:30 UTC, Elena-Bruyako requested changes
Let's improve your solution!

2024-05-09 07:30 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/controller/CategoryController.java
> +@RequestMapping("/categories")
```suggestion
@RequestMapping("/categories")
@Validated
```

2024-05-09 07:30 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/controller/CategoryController.java
> +    public List<CategoryDto> getAll() {
```suggestion
    public List<CategoryDto> getAll(@ParameterObject @PageableDefault Pageable pageable) {
```

2024-05-09 07:30 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/model/Book.java
> +    @ManyToMany(fetch = FetchType.LAZY)
ManyToMany has default FetchType.LAZY

2024-05-09 07:30 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/11-create-books-categories-table.yaml
> +            constraintName: fk_category_id
```suggestion
            constraintName: fk_category_id
            
```

2024-05-09 07:30 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/10-create-category-table.yaml
> +                    nullable: false
```suggestion
                    nullable: false
                    
```

2024-05-09 07:30 UTC, Elena-Bruyako commented on target/generated-sources/annotations/mate/academy/bookstore/mapper/impl/BookMapperImpl.java
> +public class BookMapperImpl implements BookMapper {
Please, add these to gitignore 
target/
!**/src/main/**/target/
!**/src/test/**/target/

2024-05-09 18:01 UTC, sarakhmen approved these changes
good job!

2024-05-10 08:01 UTC, merged